version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rayochat_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - rayochat
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: rayochat_nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - rayochat
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: rayochat_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: rayochat
      POSTGRES_USER: rayochat
      POSTGRES_PASSWORD: rayochat_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rayochat

  redis:
    image: redis:7-alpine
    container_name: rayochat_redis
    restart: unless-stopped
    networks:
      - rayochat

volumes:
  postgres_data:

networks:
  rayochat:
    driver: bridge
